### ISSUE TITLE
button/text entry visibility and startup options 

### ISSUE THREAD

**Issue by butterw** [tsl0922/mpv-debug-plugin#2]
1) I use `--no-input-default-bindings` 
To not show default bindings in debug, you need `--no-input-builtin-bindings`.

2) Is the default mpv msg-level `status` available ? 
- Debug seems to force verbose at startup. I've tried `--msg-level=all=info` with no success.

3) The visibility of the text entries and in particular the `Level` button needs to be improved:
- maybe a light border could be added ?

**Comment by tsl0922** [comment]
1. It's hard to identify whether a binding is builtin (not planned)
2. added `status` level now
3. `msg-level/all` is used as startup log level now
4. updated the button color

**Comment by butterw** [comment]
to get verbose messages at startup: `mpv --msg-level=all=v`

The new Level button color is good. The Filter entry would be easier to find if it was changed to `Filter:                           `  in the Console tab visible by default.

**Comment by tsl0922** [comment]
I've redesigned the console controls, it should address your comments now.

**Comment by tsl0922** [comment]
New bindings view, more info is shown now, and you can now search for key and command:

<img width="575" alt="image" src="https://github.com/tsl0922/mpv-debug-plugin/assets/1680515/4a45ec2b-4988-44cb-94f4-b50f72b8fe9a">
