### ISSUE TITLE
[REQUEST] Ability to change startup `Lines` value + general QoL enhancements

### ISSUE THREAD

**Issue by Sneakpeakcss** [tsl0922/mpv-debug-plugin#3]
- It would be good to have an option to set a custom `Lines` value that will be saved, just to avoid constantly changing it after re-opening mpv. 

In the case of `Filter`, i would say that it's more of a search box rather than a filter, which is most noticeable in console tab, and this brings the second request:

- Currently, changing `Level` only filters new messages. Would it be possible to allow it to filter already displayed messages based on chosen level? Alternatively, allowing the `Filter` to search through messages by using corresponding tags (error, warn, info, etc)

- Ability to copy selected lines. Having the whole window draggable is quite convenient, so rather than making the console selectable and losing this, then maybe allowing to make a selection by using `shift+click`, if that's even possible ?

**Comment by tsl0922** [comment]
Changed `Filter` to `Search` and increased the default Lines value to `5000`.

Other requests are not planned, such features are complex to be implemented with [imgui](https://github.com/ocornut/imgui).
