### ISSUE TITLE
Support getting option from `script-opts` ?

### ISSUE THREAD

**Issue by zhongfly** [tsl0922/mpv-debug-plugin#7]
Currently the plugin will only read options from `~~/script-opts/debug.conf`, and `script-opts` will not take effect.
Is it possible to get the options like lua's `"mp.options".read_options`?

ref: https://mpv.io/manual/master/#options-script-opts

**Comment by tsl0922** [comment]
It's possible, but why? PR welcome if you want to do it yourself.
